"""
SECUROXI AI Phase 3 Stage 3 — AI / Agent Runtime Security Layer
Protects AI applications, LLM pipelines, RAG systems, and AI agents at runtime security boundaries.
Provides input, RAG context, tool call, and output inspection before model execution or external tool calls.
"""

import re
import time
import uuid
from enum import Enum
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, field
from securoxi.logger import get_logger


class RuntimeBoundary(str, Enum):
    INPUT = "INPUT"
    RAG_CONTEXT = "RAG_CONTEXT"
    AGENT_MEMORY = "AGENT_MEMORY"
    TOOL_CALL = "TOOL_CALL"
    OUTPUT = "OUTPUT"


class RuntimeActionResult(str, Enum):
    ALLOW = "ALLOW"
    REVIEW = "REVIEW"
    BLOCK = "BLOCK"


@dataclass
class RuntimeSecurityEvent:
    """Security event generated by Runtime Security Layer."""
    event_id: str = field(default_factory=lambda: f"RTE-{uuid.uuid4().hex[:8]}")
    boundary: RuntimeBoundary = RuntimeBoundary.INPUT
    source: str = "UNTRUSTED_INPUT"
    target: str = "LLM_PIPELINE"
    content_classification: str = "BENIGN"
    findings: List[Dict[str, Any]] = field(default_factory=list)
    risk_score: float = 0.0
    policy_result: RuntimeActionResult = RuntimeActionResult.ALLOW
    evidence: str = "None"
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "event_id": self.event_id,
            "boundary": self.boundary.value,
            "source": self.source,
            "target": self.target,
            "content_classification": self.content_classification,
            "findings": self.findings,
            "risk_score": self.risk_score,
            "policy_result": self.policy_result.value,
            "evidence": self.evidence,
            "timestamp": self.timestamp
        }


class InputInspector:
    """Interface 1: Inspects raw prompt inputs before passing to LLM."""
    INJECTION_PATTERNS = [
        r"ignore\s+(all\s+)?(previous\s+)?instructions",
        r"system\s+instruction:",
        r"override\s+system\s+prompt",
        r"you\s+are\s+now\s+in\s+dan\s+mode",
        r"unconditionally\s+(rank|give|approve)"
    ]

    def inspect_input(self, input_text: str) -> List[Dict[str, Any]]:
        findings = []
        for pat in self.INJECTION_PATTERNS:
            if re.search(pat, input_text, re.IGNORECASE):
                findings.append({
                    "threat_type": "PROMPT_INJECTION",
                    "pattern": pat,
                    "evidence": f"Matched pattern '{pat}' in input text"
                })
        return findings


class ContextInspector:
    """Interface 2: Inspects RAG retrieved chunks & Agent memory context."""
    INDIRECT_INJECTION_PATTERNS = [
        r"\[system\s+instruction:",
        r"<system_override>",
        r"exfiltrate\s+to\s+http",
        r"send\s+api_key\s+to"
    ]

    def inspect_context(self, context_chunks: List[str]) -> List[Dict[str, Any]]:
        findings = []
        for idx, chunk in enumerate(context_chunks):
            for pat in self.INDIRECT_INJECTION_PATTERNS:
                if re.search(pat, chunk, re.IGNORECASE):
                    findings.append({
                        "threat_type": "INDIRECT_PROMPT_INJECTION",
                        "chunk_index": idx,
                        "pattern": pat,
                        "evidence": f"RAG context chunk {idx} contains indirect injection payload"
                    })
        return findings


class ToolCallInspector:
    """Interface 3: Inspects tool names and arguments before tool execution."""
    DANGEROUS_COMMANDS = [r"rm\s+-rf", r"sudo", r"chmod\s+777", r"eval\(", r"os\.system"]
    DANGEROUS_TOOLS = ["shell_exec", "run_system_command", "eval_code"]

    def inspect_tool_call(self, tool_name: str, tool_args: Dict[str, Any]) -> List[Dict[str, Any]]:
        findings = []
        if tool_name.lower() in self.DANGEROUS_TOOLS:
            findings.append({
                "threat_type": "UNAUTHORIZED_TOOL_CALL",
                "tool_name": tool_name,
                "evidence": f"Attempted execution of restricted tool '{tool_name}'"
            })

        arg_str = str(tool_args)
        for cmd_pat in self.DANGEROUS_COMMANDS:
            if re.search(cmd_pat, arg_str, re.IGNORECASE):
                findings.append({
                    "threat_type": "MALICIOUS_TOOL_ARGUMENT",
                    "command_pattern": cmd_pat,
                    "evidence": f"Tool argument contains dangerous shell command pattern '{cmd_pat}'"
                })

        return findings


class OutputInspector:
    """Interface 4: Inspects LLM completions for data exfiltration or policy violations."""
    EXFILTRATION_PATTERNS = [
        r"http[s]?://[^\s]+\?exfil=",
        r"!\[image\]\(http[s]?://[^\s]+\?data=",
        r"BEGIN\s+PRIVATE\s+KEY"
    ]

    def inspect_output(self, output_text: str) -> List[Dict[str, Any]]:
        findings = []
        for pat in self.EXFILTRATION_PATTERNS:
            if re.search(pat, output_text, re.IGNORECASE):
                findings.append({
                    "threat_type": "DATA_EXFILTRATION_ATTEMPT",
                    "pattern": pat,
                    "evidence": f"LLM output contains exfiltration URL/key pattern '{pat}'"
                })
        return findings


class PolicyEvaluator:
    """Interface 5: Maps risk scores & findings to policy decisions (ALLOW, REVIEW, BLOCK)."""
    def evaluate(self, findings: List[Dict[str, Any]]) -> (RuntimeActionResult, float):
        if not findings:
            return RuntimeActionResult.ALLOW, 0.0

        has_block_threat = any(
            f.get("threat_type") in [
                "PROMPT_INJECTION", "INDIRECT_PROMPT_INJECTION",
                "MALICIOUS_TOOL_ARGUMENT", "DATA_EXFILTRATION_ATTEMPT", "UNAUTHORIZED_TOOL_CALL"
            ]
            for f in findings
        )

        if has_block_threat:
            return RuntimeActionResult.BLOCK, 100.0

        return RuntimeActionResult.REVIEW, 50.0


class SecurityEventGenerator:
    """Interface 6: Generates structured RuntimeSecurityEvent objects."""
    def generate_event(
        self,
        boundary: RuntimeBoundary,
        source: str,
        target: str,
        findings: List[Dict[str, Any]],
        policy_result: RuntimeActionResult,
        risk_score: float
    ) -> RuntimeSecurityEvent:
        classification = "BENIGN" if policy_result == RuntimeActionResult.ALLOW else "MALICIOUS"
        evidence_str = "; ".join(f.get("evidence", "") for f in findings) if findings else "Passed security boundary."

        return RuntimeSecurityEvent(
            boundary=boundary,
            source=source,
            target=target,
            content_classification=classification,
            findings=findings,
            risk_score=risk_score,
            policy_result=policy_result,
            evidence=evidence_str
        )


class SecuroxiRuntimeSecurity:
    """
    Unified Securoxi Runtime Security Layer.
    Orchestrates all 6 runtime security interfaces.
    """

    def __init__(self):
        self.logger = get_logger("securoxi.brain.runtime")
        self.input_inspector = InputInspector()
        self.context_inspector = ContextInspector()
        self.tool_inspector = ToolCallInspector()
        self.output_inspector = OutputInspector()
        self.policy_evaluator = PolicyEvaluator()
        self.event_generator = SecurityEventGenerator()

    def inspect_prompt_input(self, input_text: str, source: str = "USER_INPUT") -> RuntimeSecurityEvent:
        findings = self.input_inspector.inspect_input(input_text)
        action, risk = self.policy_evaluator.evaluate(findings)
        return self.event_generator.generate_event(
            boundary=RuntimeBoundary.INPUT,
            source=source,
            target="LLM_MODEL",
            findings=findings,
            policy_result=action,
            risk_score=risk
        )

    def inspect_rag_context(self, context_chunks: List[str], source: str = "RAG_VECTOR_STORE") -> RuntimeSecurityEvent:
        findings = self.context_inspector.inspect_context(context_chunks)
        action, risk = self.policy_evaluator.evaluate(findings)
        return self.event_generator.generate_event(
            boundary=RuntimeBoundary.RAG_CONTEXT,
            source=source,
            target="LLM_PROMPT_CONTEXT",
            findings=findings,
            policy_result=action,
            risk_score=risk
        )

    def inspect_tool_execution(self, tool_name: str, tool_args: Dict[str, Any], source: str = "AI_AGENT") -> RuntimeSecurityEvent:
        findings = self.tool_inspector.inspect_tool_call(tool_name, tool_args)
        action, risk = self.policy_evaluator.evaluate(findings)
        return self.event_generator.generate_event(
            boundary=RuntimeBoundary.TOOL_CALL,
            source=source,
            target=f"TOOL_{tool_name}",
            findings=findings,
            policy_result=action,
            risk_score=risk
        )

    def inspect_model_output(self, output_text: str, source: str = "LLM_MODEL") -> RuntimeSecurityEvent:
        findings = self.output_inspector.inspect_output(output_text)
        action, risk = self.policy_evaluator.evaluate(findings)
        return self.event_generator.generate_event(
            boundary=RuntimeBoundary.OUTPUT,
            source=source,
            target="USER_RESPONSE",
            findings=findings,
            policy_result=action,
            risk_score=risk
        )
