"""
SECUROXI AI Intelligence 2.0 — Production Feedback & Controlled Adaptive Improvement Types
"""

from enum import Enum


class FeedbackCategory(str, Enum):
    # General
    INCORRECT_RESULT = "INCORRECT_RESULT"
    INCOMPLETE_RESULT = "INCOMPLETE_RESULT"
    WRONG_CITATION = "WRONG_CITATION"
    UX_PROBLEM = "UX_PROBLEM"
    
    # RAG / Retrieval
    WRONG_RETRIEVAL = "WRONG_RETRIEVAL"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
    GROUNDEDNESS_FAILURE = "GROUNDEDNESS_FAILURE"
    
    # Security
    FALSE_POSITIVE = "FALSE_POSITIVE"
    FALSE_NEGATIVE = "FALSE_NEGATIVE"
    MISCLASSIFIED_RISK = "MISCLASSIFIED_RISK"
    
    # Hiring
    WRONG_REQUIREMENT_MATCH = "WRONG_REQUIREMENT_MATCH"
    WRONG_QUALIFICATION = "WRONG_QUALIFICATION"
    WRONG_RANKING = "WRONG_RANKING"
    
    # Reliability
    TASK_FAILURE = "TASK_FAILURE"
    TOOL_FAILURE = "TOOL_FAILURE"


class FeedbackSource(str, Enum):
    USER = "USER"
    RECRUITER = "RECRUITER"
    SECURITY_ANALYST = "SECURITY_ANALYST"
    ADMIN = "ADMIN"
    SYSTEM_ALERT = "SYSTEM_ALERT"
    PRODUCTION_INCIDENT = "PRODUCTION_INCIDENT"
    EVALUATION_FAILURE = "EVALUATION_FAILURE"


class FeedbackValidationState(str, Enum):
    RECEIVED = "RECEIVED"
    TRIAGED = "TRIAGED"
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"
    IMPROVEMENT_CANDIDATE = "IMPROVEMENT_CANDIDATE"


class FeedbackSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ImprovementStatus(str, Enum):
    PROPOSED = "PROPOSED"
    UNDER_REVIEW = "UNDER_REVIEW"
    IN_EVALUATION = "IN_EVALUATION"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ROLLED_BACK = "ROLLED_BACK"
    RELEASED = "RELEASED"
