"""
SECUROXI AI Intelligence 2.0 — Cross-System Autonomous Investigation Types & Enums (Phase 8 Stage 49)
"""

from enum import Enum


class TriggerType(str, Enum):
    REPEATED_SECURITY_FINDINGS = "REPEATED_SECURITY_FINDINGS"
    CANDIDATE_SECURITY_ESCALATION = "CANDIDATE_SECURITY_ESCALATION"
    SUSPICIOUS_ATS_ACTIVITY = "SUSPICIOUS_ATS_ACTIVITY"
    KNOWLEDGE_CONFLICT = "KNOWLEDGE_CONFLICT"
    POLICY_VIOLATION_ANOMALY = "POLICY_VIOLATION_ANOMALY"


class TriggerSignificance(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class InvestigationStatus(str, Enum):
    INITIATED = "INITIATED"
    EVIDENCE_COLLECTION = "EVIDENCE_COLLECTION"
    HYPOTHESIS_TESTING = "HYPOTHESIS_TESTING"
    COMPLETED = "COMPLETED"
    UNRESOLVED = "UNRESOLVED"


class HypothesisStatus(str, Enum):
    PROPOSED = "PROPOSED"
    UNDER_TEST = "UNDER_TEST"
    SUPPORTED = "SUPPORTED"
    REFUTED = "REFUTED"
    UNRESOLVED = "UNRESOLVED"


class InvestigationFindingClass(str, Enum):
    NO_ISSUE = "NO_ISSUE"
    SUSPICIOUS = "SUSPICIOUS"
    CONFIRMED_SECURITY_ISSUE = "CONFIRMED_SECURITY_ISSUE"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    OPERATIONAL_ISSUE = "OPERATIONAL_ISSUE"
    UNRESOLVED = "UNRESOLVED"


class ResponseActionType(str, Enum):
    MONITOR = "MONITOR"
    QUARANTINE_RESOURCE = "QUARANTINE_RESOURCE"
    BLOCK_ATS_MUTATION = "BLOCK_ATS_MUTATION"
    CREATE_INCIDENT = "CREATE_INCIDENT"
    REQUEST_APPROVAL = "REQUEST_APPROVAL"
    NOTIFY_ADMIN = "NOTIFY_ADMIN"
