"""
SECUROXI AI Intelligence 2.0 — Enterprise Intelligence Marketplace Types & Enums (Phase 9 Stage 57)
"""

from enum import Enum


class PackageType(str, Enum):
    CUSTOM_AGENT = "CUSTOM_AGENT"
    CUSTOM_SKILL = "CUSTOM_SKILL"
    CUSTOM_TOOL = "CUSTOM_TOOL"
    CUSTOM_CONNECTOR = "CUSTOM_CONNECTOR"
    WORKFLOW_TEMPLATE = "WORKFLOW_TEMPLATE"
    KNOWLEDGE_PACK = "KNOWLEDGE_PACK"
    REPORT_TEMPLATE = "REPORT_TEMPLATE"
    POLICY_TEMPLATE = "POLICY_TEMPLATE"
    INTELLIGENCE_MODULE = "INTELLIGENCE_MODULE"


class PackageStatus(str, Enum):
    DRAFT = "DRAFT"
    VALIDATING = "VALIDATING"
    SECURITY_SCAN = "SECURITY_SCAN"
    EVALUATION = "EVALUATION"
    REVIEW = "REVIEW"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"
    REJECTED = "REJECTED"
    DISABLED = "DISABLED"
    REVOKED = "REVOKED"
    DEPRECATED = "DEPRECATED"


class VisibilityScope(str, Enum):
    PRIVATE = "PRIVATE"
    ORGANIZATION = "ORGANIZATION"
    SELECTED_ORGANIZATIONS = "SELECTED_ORGANIZATIONS"
    PARTNER = "PARTNER"
    PUBLIC = "PUBLIC"


class PublisherTrustLevel(str, Enum):
    UNVERIFIED = "UNVERIFIED"
    VERIFIED_ORGANIZATION = "VERIFIED_ORGANIZATION"
    TRUSTED_PUBLISHER = "TRUSTED_PUBLISHER"


class PackageRiskLevel(str, Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class InstallationStatus(str, Enum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"
    ROLLED_BACK = "ROLLED_BACK"
    REVOKED = "REVOKED"
