"""
SECUROXI AI Intelligence 2.0 — Continuous Enterprise Intelligence Types & Enums (Phase 8)
"""

from enum import Enum


class EventCategory(str, Enum):
    SECURITY = "SECURITY"
    HIRING = "HIRING"
    TASK = "TASK"
    INTEGRATION = "INTEGRATION"
    DATA_GOVERNANCE = "DATA_GOVERNANCE"
    SYSTEM = "SYSTEM"


class EventTrustLevel(str, Enum):
    AUTHORITATIVE_SYSTEM = "AUTHORITATIVE_SYSTEM"
    VERIFIED_PROVIDER = "VERIFIED_PROVIDER"
    VERIFIED_APPLICATION = "VERIFIED_APPLICATION"
    USER_ACTION = "USER_ACTION"
    AGENT_ADVISORY = "AGENT_ADVISORY"
    EXTERNAL_UNTRUSTED = "EXTERNAL_UNTRUSTED"


class EventSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    NORMAL = "NORMAL"
    LOW = "LOW"


class SignalType(str, Enum):
    ANOMALOUS_ACTIVITY = "ANOMALOUS_ACTIVITY"
    REPEATED_SECURITY_FINDINGS = "REPEATED_SECURITY_FINDINGS"
    SUSPICIOUS_CANDIDATE_ACTIVITY = "SUSPICIOUS_CANDIDATE_ACTIVITY"
    INTEGRATION_ANOMALY = "INTEGRATION_ANOMALY"
    TASK_FAILURE_CLUSTER = "TASK_FAILURE_CLUSTER"
    UNUSUAL_ACCESS_PATTERN = "UNUSUAL_ACCESS_PATTERN"
    RECURRING_PROMPT_INJECTION = "RECURRING_PROMPT_INJECTION"
    CROSS_SYSTEM_ACTIVITY = "CROSS_SYSTEM_ACTIVITY"


class SignalStatus(str, Enum):
    DETECTED = "DETECTED"
    ENRICHED = "ENRICHED"
    UNDER_REVIEW = "UNDER_REVIEW"
    CONFIRMED = "CONFIRMED"
    DISMISSED = "DISMISSED"
    EXPIRED = "EXPIRED"


class HypothesisStatus(str, Enum):
    PROPOSED = "PROPOSED"
    SUPPORTED = "SUPPORTED"
    REFUTED = "REFUTED"
    ACCEPTED_BY_ANALYST = "ACCEPTED_BY_ANALYST"
