"""
SECUROXI AI Intelligence 2.0 — Autonomous Platform Operations Types & Enums (Phase 9 Stage 59)
"""

from enum import Enum


class ServiceHealthStatus(str, Enum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
    RECOVERING = "RECOVERING"
    UNKNOWN = "UNKNOWN"


class RemediationActionType(str, Enum):
    RETRY_TASK = "RETRY_TASK"
    REQUEUE_TASK = "REQUEUE_TASK"
    RESTART_WORKER = "RESTART_WORKER"
    CLEAR_SAFE_CACHE = "CLEAR_SAFE_CACHE"
    REFRESH_INDEX = "REFRESH_INDEX"
    PAUSE_WORKFLOW = "PAUSE_WORKFLOW"
    REDUCE_CONCURRENCY = "REDUCE_CONCURRENCY"
    FAILOVER_PROVIDER = "FAILOVER_PROVIDER"


class RemediationRisk(str, Enum):
    LOW_SAFE_AUTO = "LOW_SAFE_AUTO"
    MODERATE_APPROVAL_REQUIRED = "MODERATE_APPROVAL_REQUIRED"
    HIGH_APPROVAL_REQUIRED = "HIGH_APPROVAL_REQUIRED"
    CRITICAL_PROHIBITED = "CRITICAL_PROHIBITED"


class RemediationExecutionStatus(str, Enum):
    PROPOSED = "PROPOSED"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    EXECUTION_UNKNOWN = "EXECUTION_UNKNOWN"
    ROLLED_BACK = "ROLLED_BACK"
    BLOCKED_KILL_SWITCH = "BLOCKED_KILL_SWITCH"
