"""
SECUROXI AI Intelligence 2.0 — Autonomous Hiring Intelligence Types & Enums (Phase 8 Stage 47)
"""

from enum import Enum


class ChangeSignificance(str, Enum):
    NO_IMPACT = "NO_IMPACT"
    LOW_IMPACT = "LOW_IMPACT"
    MATERIAL = "MATERIAL"
    HIGH_IMPACT = "HIGH_IMPACT"
    SECURITY_CRITICAL = "SECURITY_CRITICAL"


class CandidateChangeType(str, Enum):
    NEW_CANDIDATE = "NEW_CANDIDATE"
    RESUME_UPDATED = "RESUME_UPDATED"
    ATS_STAGE_CHANGED = "ATS_STAGE_CHANGED"
    EVIDENCE_ADDED = "EVIDENCE_ADDED"
    EVIDENCE_REMOVED = "EVIDENCE_REMOVED"
    SECURITY_STATE_CHANGED = "SECURITY_STATE_CHANGED"
    FIT_SCORE_CHANGED = "FIT_SCORE_CHANGED"
    RANK_CHANGED = "RANK_CHANGED"
    JD_CHANGED = "JD_CHANGED"
    REQUIREMENT_CHANGED = "REQUIREMENT_CHANGED"


class HiringSignalType(str, Enum):
    NEW_STRONG_CANDIDATE = "NEW_STRONG_CANDIDATE"
    CANDIDATE_ENTERED_TOP_K = "CANDIDATE_ENTERED_TOP_K"
    CANDIDATE_LEFT_TOP_K = "CANDIDATE_LEFT_TOP_K"
    QUALIFICATION_CHANGED = "QUALIFICATION_CHANGED"
    MANDATORY_REQUIREMENT_FAILED = "MANDATORY_REQUIREMENT_FAILED"
    MANDATORY_REQUIREMENT_SATISFIED = "MANDATORY_REQUIREMENT_SATISFIED"
    NEW_SECURITY_RISK = "NEW_SECURITY_RISK"
    STALE_EVALUATION = "STALE_EVALUATION"
    ATS_STAGE_ANOMALY = "ATS_STAGE_ANOMALY"


class WatchStatus(str, Enum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    EXPIRED = "EXPIRED"


class RecommendationStatus(str, Enum):
    PROPOSED = "PROPOSED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
