"""
SECUROXI AI Intelligence 2.0 — Security Agent Types & Enums
Defines investigation states, recommendation types, and evidence verification tiers.
"""

from enum import Enum


class SecurityInvestigationState(str, Enum):
    """Lifecycle progress of a security investigation."""
    INITIAL_TRIAGE = "INITIAL_TRIAGE"
    EVIDENCE_GATHERING = "EVIDENCE_GATHERING"
    CORRELATION_ANALYSIS = "CORRELATION_ANALYSIS"
    SECURITY_BRAIN_ESCALATION = "SECURITY_BRAIN_ESCALATION"
    POLICY_VERIFICATION = "POLICY_VERIFICATION"
    INCIDENT_PREPARATION = "INCIDENT_PREPARATION"
    INVESTIGATION_COMPLETE = "INVESTIGATION_COMPLETE"


class SecurityRecommendationType(str, Enum):
    """Machine-readable recommendation categories generated by the Security Agent."""
    VIEW_EVIDENCE = "VIEW_EVIDENCE"
    OPEN_SECURITY_BRAIN = "OPEN_SECURITY_BRAIN"
    REVIEW_DOCUMENT = "REVIEW_DOCUMENT"
    CREATE_INCIDENT = "CREATE_INCIDENT"
    VIEW_POLICY = "VIEW_POLICY"
    RETRY_OCR = "RETRY_OCR"
    NO_ACTION = "NO_ACTION"


class EvidenceVerificationState(str, Enum):
    """Verification tiers distinguishing facts from inferred reasoning."""
    VERIFIED = "VERIFIED"        # Sourced directly from deterministic scanner
    SUPPORTED = "SUPPORTED"      # Correlated by Security Brain graph
    ADVISORY = "ADVISORY"        # Synthesized reasoning or suggestion
    UNVERIFIED = "UNVERIFIED"    # Missing raw source confirmation
