"""
SECUROXI AI Intelligence 2.0 — Controlled Autonomous Action Types & Enums (Phase 8 Stage 52)
"""

from enum import Enum


class AutonomyLevel(str, Enum):
    L0_NO_ACTION = "L0_NO_ACTION"
    L1_RECOMMENDATION_ONLY = "L1_RECOMMENDATION_ONLY"
    L2_HUMAN_APPROVAL_REQUIRED = "L2_HUMAN_APPROVAL_REQUIRED"
    L3_GUARDED_AUTONOMOUS_LOW_IMPACT = "L3_GUARDED_AUTONOMOUS_LOW_IMPACT"
    L4_RESTRICTED_WORKFLOWS = "L4_RESTRICTED_WORKFLOWS"


class ActionImpactClass(str, Enum):
    READ_ONLY = "READ_ONLY"
    LOW_IMPACT_REVERSIBLE = "LOW_IMPACT_REVERSIBLE"
    MODERATE_IMPACT = "MODERATE_IMPACT"
    HIGH_IMPACT = "HIGH_IMPACT"
    CRITICAL = "CRITICAL"


class ActionReversibility(str, Enum):
    REVERSIBLE = "REVERSIBLE"
    PARTIALLY_REVERSIBLE = "PARTIALLY_REVERSIBLE"
    IRREVERSIBLE = "IRREVERSIBLE"


class ProposalStatus(str, Enum):
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXECUTED = "EXECUTED"
    STALE_PROPOSAL = "STALE_PROPOSAL"
    DENIED_POLICY = "DENIED_POLICY"


class ExecutionStatus(str, Enum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    UNKNOWN_OUTCOME = "UNKNOWN_OUTCOME"
    ROLLED_BACK = "ROLLED_BACK"
